### ISSUE TITLE
Settings / Innstillinger not yet translated?

### ISSUE THREAD

**Issue by Protx** [miui-scandinavia/MA-XML-8.0-NORWEGIAN#1]
Just a Heads Up. 
I don't know if it is an real issue or just not yet translated, but the last couple of miui 8 eu releases has not had Norwegian language under Settings.

xiaomi.eu_multi_MI3WMI4W_6.7.21_v8-6.0
MI4

**Comment by datagutt** [comment]
Hey,
I was not aware of this, my Mi4c doesn't support 6.0 yet. I will ask @ingbrzy why this is happening.

**Comment by Protx** [comment]
I see that what I wrote came out a bit wrong.
To clarify, I can choose Norwegian Language and it works, but everything in the "Settings" screen is not translated and in English. 
But a lot of apps is translated and in Norwegian. 
Edit: changed the misleading title.

**Comment by Protx** [comment]
I think the issue is that there is a Settings.apk translation in MA-XML-8.0-NORWEGIAN/Norwegian/device/cancro. And since the files in "device" has priority it means that the Settings.apk translation in "main" is not used for this device?
Same goes for other devices like gemini (MI5).

**Comment by datagutt** [comment]
Hey,
You are right (i suspected it but hadn't got the chance to look at it yet). Looks like i used values-nb, instead of values-nb-rNO. So instead of overlaying with device-specific resources, i was replacing the main ones instead.
This fix might be in tommorows .eu release, but @ingbrzy usually compiles the ROM a day in advance, so we might have to wait a week for it.
Thanks for your help!

**Comment by datagutt** [comment]
Looks like the release will be postponed to weekend, so this fix and whatever translation i do up until then will be included :)
